from __future__ import annotations

MORPHOLOGY_COLUMNS = [
    "OldChordDistribution",
    "OpenAngle",
    "CVD",
    "AverageDistance",
    "LengthVolumeRatio",
    "LengthAreaRatio",
    "JunctionArea",
    "Length",
    "Area",
    "Volume",
    "ConvexHullVolume",
    "ConvexHullRatio",
]

SPINES_INFO_COLUMNS = [
    "dataset",
    "neuron_id",
    "limb_id",
    "original_branch_id",
    "merged_branch_id",
    "spine_id",
    "source_mesh_path",
    "sealed_mesh_path",
    "local_mesh_path",
    "local_sealed_mesh_path",
    "species",
    "health",
    "cell_type",
    "cell_type_binary",
    "compartment",
    "attachment_center_global_x",
    "attachment_center_global_y",
    "attachment_center_global_z",
    "attachment_projection_x",
    "attachment_projection_y",
    "attachment_projection_z",
    "attachment_boundary_perimeter",
    "attachment_boundary_area",
    "tangent_x",
    "tangent_y",
    "tangent_z",
    "radial_x",
    "radial_y",
    "radial_z",
    "binormal_x",
    "binormal_y",
    "binormal_z",
    "source_vertices",
    "source_faces",
    "n_boundary_loops_before",
    "is_watertight_after",
    "is_manifold_after",
    "n_connected_components",
    "detect_status",
    "seal_status",
    "canonicalize_status",
    "merge_metadata_status",
    "processing_version",
    "config_hash",
]

SPINE_MORPHOLOGY_COLUMNS = [
    "dataset",
    "neuron_id",
    "limb_id",
    "original_branch_id",
    "spine_id",
    "morphology_status",
    "morphology_error",
    *MORPHOLOGY_COLUMNS,
    "processing_version",
    "config_hash",
]
